// data.jsx — mock data for SchoolHub. Bilingual where the source data is user-facing.

const SH_DATA = {
  meal: {
    today: {
      date: "2026.05.21",
      day: "목",
      kcal: 814,
      items: [
        { ko: "현미밥", en: "Brown rice", allergens: [] },
        { ko: "쇠고기 미역국", en: "Beef seaweed soup", allergens: ["5", "16"] },
        { ko: "제육볶음", en: "Stir-fried pork", allergens: ["5", "6", "10", "13"] },
        { ko: "계란말이", en: "Egg roll", allergens: ["1", "5"] },
        { ko: "배추김치", en: "Kimchi", allergens: ["9"] },
        { ko: "요거트", en: "Yogurt", allergens: ["2"] },
      ],
    },
    week: [
      { day: "월", date: "5.18", kcal: 782, items: ["잡곡밥", "북엇국", "닭갈비", "콩나물무침", "깍두기"] },
      { day: "화", date: "5.19", kcal: 798, items: ["흰밥", "된장찌개", "고등어구이", "시금치나물", "배추김치"] },
      { day: "수", date: "5.20", kcal: 836, items: ["크림스파게티", "갈릭빵", "치즈볼", "양배추샐러드", "방울토마토"] },
      { day: "목", date: "5.21", kcal: 814, items: ["현미밥", "쇠고기 미역국", "제육볶음", "계란말이", "배추김치"], today: true },
      { day: "금", date: "5.22", kcal: 760, items: ["기장밥", "어묵국", "돈가스", "포테이토샐러드", "단무지"] },
    ],
    allergyKey: [
      { n: "1", ko: "난류", en: "Eggs" },
      { n: "2", ko: "우유", en: "Milk" },
      { n: "5", ko: "대두", en: "Soy" },
      { n: "6", ko: "밀", en: "Wheat" },
      { n: "9", ko: "고등어", en: "Mackerel" },
      { n: "10", ko: "돼지고기", en: "Pork" },
      { n: "13", ko: "토마토", en: "Tomato" },
      { n: "16", ko: "쇠고기", en: "Beef" },
    ],
  },

  timetable: {
    today: [
      { period: 1, subject_ko: "수학", subject_en: "Math", teacher: "박지원", room: "본관 305", time: "09:00–09:45", color: "#3182F6" },
      { period: 2, subject_ko: "영어", subject_en: "English", teacher: "이수연", room: "본관 305", time: "09:55–10:40", color: "#7A5AE0", now: true },
      { period: 3, subject_ko: "체육", subject_en: "PE", teacher: "최도현", room: "체육관", time: "10:50–11:35", color: "#FF9000" },
      { period: 4, subject_ko: "국어", subject_en: "Korean", teacher: "정민지", room: "본관 305", time: "11:45–12:30", color: "#F04452" },
      { period: 5, subject_ko: "과학", subject_en: "Science", teacher: "한승호", room: "과학실 2", time: "13:30–14:15", color: "#007B33" },
      { period: 6, subject_ko: "음악", subject_en: "Music", teacher: "오세린", room: "음악실", time: "14:25–15:10", color: "#FFB400" },
      { period: 7, subject_ko: "기술가정", subject_en: "Tech & Home", teacher: "강은영", room: "기가실", time: "15:20–16:05", color: "#1B64DA" },
    ],
    week: {
      days: ["월", "화", "수", "목", "금"],
      grid: [
        // 7 periods × 5 days
        ["국어", "영어", "수학", "수학", "체육"],
        ["사회", "수학", "영어", "영어", "국어"],
        ["과학", "체육", "국어", "체육", "기가"],
        ["수학", "국어", "사회", "국어", "사회"],
        ["미술", "도덕", "과학", "과학", "음악"],
        ["미술", "도덕", "음악", "음악", "동아리"],
        ["창체", "기가", "기가", "기가", "동아리"],
      ],
    },
  },

  notices: [
    { id: "n1", tag: "공지", title: "1학기 기말고사 시험 범위 공지", time_ko: "2시간 전", time_en: "2h ago", pinned: true },
    { id: "n2", tag: "가정통신문", title: "현장체험학습(5/28) 안내 및 신청서 배부", time_ko: "어제", time_en: "yesterday" },
    { id: "n3", tag: "학생회", title: "2026 학생회장 선거 후보 등록 안내", time_ko: "2일 전", time_en: "2d ago" },
  ],

  calendar: {
    month: 5, year: 2026,
    events: {
      "2026-05-21": [{ title_ko: "수학 수행평가", title_en: "Math assessment", type: "exam" }],
      "2026-05-23": [{ title_ko: "1학년 학부모 상담", title_en: "G1 parent meeting", type: "meeting" }],
      "2026-05-28": [{ title_ko: "현장체험학습", title_en: "Field trip", type: "trip" }],
      "2026-05-29": [{ title_ko: "재량휴업일", title_en: "School holiday", type: "holiday" }],
      "2026-06-03": [{ title_ko: "지방선거(임시휴업)", title_en: "Local election", type: "holiday" }],
      "2026-06-15": [{ title_ko: "1학기 기말고사", title_en: "Final exams", type: "exam" }],
      "2026-06-16": [{ title_ko: "1학기 기말고사", title_en: "Final exams", type: "exam" }],
      "2026-06-17": [{ title_ko: "1학기 기말고사", title_en: "Final exams", type: "exam" }],
    },
  },

  lostItems: [
    {
      id: "l1", category: "lost", icon: "📱", color: "#FFE9EB", iconColor: "#F04452",
      title_ko: "검정 아이폰 14 (케이스 있음)",
      title_en: "Black iPhone 14 with case",
      place_ko: "3층 음수대 옆",
      place_en: "Next to 3F water fountain",
      date: "2026.05.20",
      desc_ko: "투명 케이스에 인스타 스티커가 붙어 있어요. 잠금화면에 강아지 사진 있어요.",
      desc_en: "Clear case with Insta stickers. Dog photo on lock screen.",
      status: "open", postedBy: "익명", time_ko: "1시간 전", time_en: "1h ago",
    },
    {
      id: "l2", category: "found", icon: "🔑", color: "#FFF6DD", iconColor: "#B58300",
      title_ko: "은색 열쇠고리 + 키 3개",
      title_en: "Silver keyring with 3 keys",
      place_ko: "강당 무대 옆",
      place_en: "Beside auditorium stage",
      date: "2026.05.20",
      desc_ko: "토끼 캐릭터 키링이 달려 있어요. 행정실에 보관중이에요.",
      desc_en: "Has a rabbit charm. Held at admin office.",
      status: "keep", postedBy: "행정실", time_ko: "3시간 전", time_en: "3h ago",
    },
    {
      id: "l3", category: "found", icon: "🎒", color: "#E8F1FE", iconColor: "#1B64DA",
      title_ko: "네이비 아디다스 백팩",
      title_en: "Navy Adidas backpack",
      place_ko: "2학년 7반 앞 복도",
      place_en: "Hallway in front of 2-7",
      date: "2026.05.19",
      desc_ko: "안에 수학 교과서와 노트가 들어있어요. 이름표는 떼어져 있어요.",
      desc_en: "Math textbook and notebook inside. Name tag removed.",
      status: "keep", postedBy: "학생회 분실물팀", time_ko: "어제", time_en: "yesterday",
    },
    {
      id: "l4", category: "lost", icon: "🥤", color: "#E6F4ED", iconColor: "#007B33",
      title_ko: "민트색 스타벅스 텀블러",
      title_en: "Mint Starbucks tumbler",
      place_ko: "급식실 근처",
      place_en: "Near cafeteria",
      date: "2026.05.18",
      desc_ko: "바닥에 작은 흠집이 있고, 이름 'JU' 라벨이 붙어 있어요.",
      desc_en: "Small scratch on bottom, sticker reading 'JU'.",
      status: "done", postedBy: "익명", time_ko: "3일 전", time_en: "3d ago",
    },
    {
      id: "l5", category: "found", icon: "🎧", color: "#F5EBFF", iconColor: "#6E40C9",
      title_ko: "흰색 에어팟 프로 케이스",
      title_en: "White AirPods Pro case",
      place_ko: "도서관 1층 열람실",
      place_en: "Library 1F reading room",
      date: "2026.05.20",
      desc_ko: "케이스만 발견됐어요. 본체는 아직 못 찾았어요.",
      desc_en: "Case only — earphones not found.",
      status: "keep", postedBy: "도서부", time_ko: "5시간 전", time_en: "5h ago",
    },
    {
      id: "l6", category: "lost", icon: "📓", color: "#FFF1DD", iconColor: "#FF9000",
      title_ko: "수학 노트 (3-5 김다온)",
      title_en: "Math notebook (3-5 Kim Daon)",
      place_ko: "급식실 또는 본관 3층",
      place_en: "Cafeteria or 3F",
      date: "2026.05.19",
      desc_ko: "표지에 별 스티커 4개가 붙어 있어요. 안에 시험 정리가 들어있어요.",
      desc_en: "Four star stickers on cover. Test notes inside.",
      status: "open", postedBy: "김다온", time_ko: "어제", time_en: "yesterday",
    },
  ],

  suggestions: [
    {
      id: "s1", title_ko: "급식실 줄 서는 동선 개선해 주세요",
      title_en: "Please redesign the cafeteria queue",
      body_ko: "지금 동선이 너무 좁아서 1학년이랑 부딪혀요. 한쪽 방향으로만 가게 해주시면 좋겠어요.",
      body_en: "The path is too narrow and we keep bumping into 1st graders. One-way flow would help.",
      likes: 247, status: "done", author: "익명", time_ko: "3일 전", time_en: "3d ago",
      reply_ko: "5월 마지막 주부터 일방통행으로 운영해요. 감사합니다!",
      reply_en: "One-way flow starts the last week of May. Thank you!",
    },
    {
      id: "s2", title_ko: "체육복 입고 등교하는 날 늘려주세요",
      title_en: "More days where we can wear PE uniforms",
      body_ko: "체육 있는 날은 아침부터 체육복 입고 등교하게 해주세요. 갈아입을 시간이 부족해요.",
      body_en: "On PE days, let us wear PE uniforms from morning — changing time is tight.",
      likes: 189, status: "review", author: "익명", time_ko: "6일 전", time_en: "6d ago",
    },
    {
      id: "s3", title_ko: "도서관 자습실 자리 예약제 도입",
      title_en: "Reservation system for library study room",
      body_ko: "시험기간만이라도 자리 예약제로 운영하면 좋겠어요.",
      body_en: "At least during exam season, a reservation system would help.",
      likes: 156, status: "review", author: "익명", time_ko: "1주 전", time_en: "1w ago",
    },
    {
      id: "s4", title_ko: "축제 부스 신청 기간 더 길게",
      title_en: "Longer festival booth application period",
      body_ko: "3일은 너무 짧아요. 학원이나 다른 일정 있으면 놓치게 돼요.",
      body_en: "3 days is too short — easy to miss if you have other plans.",
      likes: 98, status: "open", author: "익명", time_ko: "2일 전", time_en: "2d ago",
    },
    {
      id: "s5", title_ko: "에어컨 좀 일찍 켜주세요",
      title_en: "Turn on the AC earlier",
      body_ko: "오전 10시쯤 되면 너무 더워요. 9시부터 켜주시면 좋겠어요.",
      body_en: "By 10am the heat is rough — please start at 9.",
      likes: 312, status: "review", author: "익명", time_ko: "5일 전", time_en: "5d ago",
    },
  ],

  forms: [
    { id: "f1", title_ko: "교외 체험학습 신청서", title_en: "Off-campus learning request", fmt: "HWP", size: 142, recent: 286 },
    { id: "f2", title_ko: "결석계", title_en: "Absence form", fmt: "HWP", size: 88, recent: 174 },
    { id: "f3", title_ko: "교외 체험학습 보고서", title_en: "Off-campus report", fmt: "HWP", size: 156, recent: 142 },
    { id: "f4", title_ko: "조퇴 신청서", title_en: "Early dismissal request", fmt: "PDF", size: 64, recent: 98 },
    { id: "f5", title_ko: "지각 사유서", title_en: "Late arrival statement", fmt: "PDF", size: 58, recent: 76 },
    { id: "f6", title_ko: "학교 행사 참가 동의서", title_en: "School event consent", fmt: "PDF", size: 102, recent: 54 },
    { id: "f7", title_ko: "현장체험학습 보호자 동의서", title_en: "Field trip parent consent", fmt: "HWP", size: 124, recent: 41 },
    { id: "f8", title_ko: "방과후학교 수강 신청서", title_en: "After-school course application", fmt: "HWP", size: 188, recent: 38 },
  ],

  exams: [
    { id: "e1", subject: "수학", subjectEn: "Math", grade: 3, year: 2025, term: 1, type: "기말", count: 24 },
    { id: "e2", subject: "수학", subjectEn: "Math", grade: 3, year: 2025, term: 1, type: "중간", count: 22 },
    { id: "e3", subject: "영어", subjectEn: "English", grade: 3, year: 2025, term: 1, type: "기말", count: 30 },
    { id: "e4", subject: "국어", subjectEn: "Korean", grade: 3, year: 2025, term: 1, type: "기말", count: 28 },
    { id: "e5", subject: "사회", subjectEn: "Social", grade: 3, year: 2025, term: 1, type: "기말", count: 25 },
    { id: "e6", subject: "과학", subjectEn: "Science", grade: 3, year: 2025, term: 2, type: "중간", count: 26 },
    { id: "e7", subject: "수학", subjectEn: "Math", grade: 2, year: 2024, term: 1, type: "기말", count: 20 },
    { id: "e8", subject: "영어", subjectEn: "English", grade: 2, year: 2024, term: 1, type: "기말", count: 28 },
  ],

  quote: { text: "청춘! 그것은 행운이다.", author: "" },
  ddays: [],
};

window.SH_DATA = SH_DATA;
